# Generated by Django 3.2 on 2021-05-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct_scans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='scanId',
            field=models.CharField(default='123', max_length=255),
            preserve_default=False,
        ),
    ]
